
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4

    - name: Install Nix
      uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Install nix dependencies
      env:
        WITH_SHELL: "nix-shell --pure --run"
      run: ${WITH_SHELL} 'echo hello'

    - name: 2016-dpg
      env:
        WITH_SHELL: "nix-shell --pure --run"
        POSTER: ./2016-dpg/
      run: cd ${POSTER} && ${WITH_SHELL} make

    - name: 2018-menton
      env:
        WITH_SHELL: "nix-shell --pure --run"
        POSTER: ./2018-menton/
      run: cd ${POSTER} && ${WITH_SHELL} make

    - name: 2019-mqm-heidelberg
      env:
        WITH_SHELL: "nix-shell --pure --run"
        POSTER: 2019-mqm-heidelberg
      run: cd ${POSTER} && ${WITH_SHELL} make

    - name: 2022-psik-lausanne
      env:
        WITH_SHELL: "nix-shell --pure --run"
        POSTER: 2022-psik-lausanne
      run: cd ${POSTER} && ${WITH_SHELL} make

    - name: 2022-PRACE-paris
      env:
        WITH_SHELL: "nix-shell --pure --run"
        POSTER: 2022-PRACE-paris
      run: cd ${POSTER} && ${WITH_SHELL} make

    - name: group/2022-cecam-lausanne-cc4s
      env:
        WITH_SHELL: "nix-shell --pure --run"
        POSTER: group/2022-cecam-lausanne-cc4s
      run: cd ${POSTER} && ${WITH_SHELL} make

